# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooling_id', models.CharField(max_length=50, unique=True, verbose_name='工装编号')),
                ('name', models.CharField(max_length=200, verbose_name='工装名称')),
                ('type', models.CharField(max_length=100, verbose_name='工装类型')),
                ('model', models.CharField(max_length=100, verbose_name='工装型号')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='采购价格')),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '维护中'), ('repair', '维修中'), ('retired', '已报废')], default='available', max_length=20, verbose_name='工装状态')),
                ('location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('specifications', models.TextField(verbose_name='技术规格')),
                ('material', models.CharField(max_length=100, verbose_name='材质')),
                ('dimensions', models.CharField(max_length=200, verbose_name='尺寸规格')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='重量(kg)')),
                ('max_load', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大载荷(N)')),
                ('operating_temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='最低工作温度(°C)')),
                ('operating_temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='最高工作温度(°C)')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次维护日期')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('maintenance_interval', models.IntegerField(default=90, verbose_name='维护间隔(天)')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工装',
                'verbose_name_plural': '工装',
                'db_table': 'tooling',
                'ordering': ['tooling_id'],
            },
        ),
        migrations.CreateModel(
            name='ToolingMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', '例行维护'), ('preventive', '预防性维护'), ('corrective', '纠正性维护'), ('calibration', '校准')], max_length=20, verbose_name='维护类型')),
                ('maintenance_date', models.DateField(verbose_name='维护日期')),
                ('maintenance_content', models.TextField(verbose_name='维护内容')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='更换部件')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='维护费用')),
                ('calibration_certificate', models.FileField(blank=True, null=True, upload_to='tooling_calibration/', verbose_name='校准证书')),
                ('calibration_due_date', models.DateField(blank=True, null=True, verbose_name='校准到期日期')),
                ('maintenance_result', models.CharField(choices=[('completed', '完成'), ('pending', '待完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='维护结果')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工装维护记录',
                'verbose_name_plural': '工装维护记录',
                'db_table': 'tooling_maintenance',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='ToolingUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始使用时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束使用时间')),
                ('usage_purpose', models.CharField(max_length=200, verbose_name='使用目的')),
                ('usage_notes', models.TextField(blank=True, verbose_name='使用说明')),
                ('load_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='施加载荷(N)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='使用温度(°C)')),
                ('tooling_condition', models.CharField(choices=[('normal', '正常'), ('wear', '磨损'), ('damaged', '损坏')], default='normal', max_length=20, verbose_name='工装状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='关联试验任务')),
                ('tooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooling.tooling', verbose_name='工装')),
            ],
            options={
                'verbose_name': '工装使用记录',
                'verbose_name_plural': '工装使用记录',
                'db_table': 'tooling_usage_records',
                'ordering': ['-start_time'],
            },
        ),
    ]
