# Generated by Django 4.2.7 on 2026-01-07 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tooling', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooling',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tooling_attachments/', verbose_name='技术文档'),
        ),
        migrations.AddField(
            model_name='tooling',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tooling_images/', verbose_name='工装图片'),
        ),
        migrations.AlterField(
            model_name='tooling',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '维护中'), ('repair', '维修中'), ('retired', '已报废'), ('scrap_pending', '报废申请中')], default='available', max_length=20, verbose_name='工装状态'),
        ),
        migrations.CreateModel(
            name='ToolingScrapApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('reason', models.TextField(verbose_name='报废原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='申请状态')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='审批日期')),
                ('approval_note', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scraps', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('tooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooling.tooling', verbose_name='工装')),
            ],
            options={
                'verbose_name': '工装报废申请',
                'verbose_name_plural': '工装报废申请',
                'db_table': 'tooling_scrap_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('purpose', models.CharField(max_length=200, verbose_name='使用目的')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='预约状态')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooling_reservations', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('tooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooling.tooling', verbose_name='工装')),
            ],
            options={
                'verbose_name': '工装预约',
                'verbose_name_plural': '工装预约',
                'db_table': 'tooling_reservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
