# Generated by Django 4.2.7 on 2026-02-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0003_tooling_attachment_tooling_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolingscrapapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='toolingscrapapplication',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='toolingscrapapplication',
            name='tooling',
        ),
        migrations.RemoveField(
            model_name='tooling',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='tooling',
            name='image',
        ),
        migrations.AlterField(
            model_name='tooling',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '维护中'), ('repair', '维修中'), ('retired', '已报废')], default='available', max_length=20, verbose_name='工装状态'),
        ),
        migrations.DeleteModel(
            name='ToolingReservation',
        ),
        migrations.DeleteModel(
            name='ToolingScrapApplication',
        ),
    ]
