# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='优先级名称')),
                ('level', models.IntegerField(unique=True, verbose_name='优先级等级')),
                ('description', models.TextField(blank=True, verbose_name='优先级描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '优先级类型',
                'verbose_name_plural': '优先级类型',
                'db_table': 'priority_types',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='状态名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='状态代码')),
                ('description', models.TextField(blank=True, verbose_name='状态描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务状态',
                'verbose_name_plural': '任务状态',
                'db_table': 'task_status',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('test_outline', models.TextField(blank=True, verbose_name='试验大纲')),
                ('test_report', models.TextField(blank=True, verbose_name='试验报告')),
                ('test_outline_file', models.FileField(blank=True, null=True, upload_to='test_outlines/', verbose_name='试验大纲文件')),
                ('test_report_file', models.FileField(blank=True, null=True, upload_to='test_reports/', verbose_name='试验报告文件')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试验任务',
                'verbose_name_plural': '试验任务',
                'db_table': 'test_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='试验类型名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='试验类型代码')),
                ('description', models.TextField(blank=True, verbose_name='试验类型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '试验类型',
                'verbose_name_plural': '试验类型',
                'db_table': 'test_types',
            },
        ),
    ]
