# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.prioritytype', verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tasks', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskstatus', verbose_name='任务状态'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtype', verbose_name='试验类型'),
        ),
    ]
