# Generated by Django 4.2.7 on 2025-11-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='requester_department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='申请人部门'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='requester_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='申请人姓名'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='requester_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='申请人手机号'),
        ),
    ]
