# Generated by Django 4.2.7 on 2025-11-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_testtask_requester_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='拒绝理由'),
        ),
    ]
