# Generated by Django 4.2.7 on 2025-11-12 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_testtask_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_number', models.CharField(max_length=50, unique=True, verbose_name='子任务编号')),
                ('subtask_name', models.CharField(max_length=200, verbose_name='子任务名称')),
                ('description', models.TextField(blank=True, verbose_name='子任务描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='实际开始日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.testtask', verbose_name='主任务')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskstatus', verbose_name='状态')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtype', verbose_name='试验类型')),
            ],
            options={
                'verbose_name': '子任务',
                'verbose_name_plural': '子任务',
                'db_table': 'sub_tasks',
                'ordering': ['subtask_number'],
            },
        ),
        migrations.CreateModel(
            name='SubTaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_conditions', models.TextField(blank=True, verbose_name='试验条件')),
                ('test_method', models.TextField(blank=True, verbose_name='试验方法')),
                ('test_equipment', models.TextField(blank=True, verbose_name='试验设备')),
                ('test_data', models.JSONField(blank=True, default=dict, verbose_name='试验数据')),
                ('test_result', models.TextField(blank=True, verbose_name='试验结果')),
                ('test_conclusion', models.TextField(blank=True, verbose_name='试验结论')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='subtask_data/', verbose_name='数据文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subtask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='tasks.subtask', verbose_name='子任务')),
            ],
            options={
                'verbose_name': '子任务数据',
                'verbose_name_plural': '子任务数据',
                'db_table': 'subtask_data',
            },
        ),
    ]
