# Generated by Django 4.2.7 on 2025-11-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_subtask_subtaskdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscSpringTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(max_length=50, unique=True, verbose_name='试验编号')),
                ('batch_number', models.CharField(max_length=100, verbose_name='批次号')),
                ('batch_total', models.IntegerField(verbose_name='本批次总数')),
                ('test_quantity', models.IntegerField(verbose_name='试验数量')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商')),
                ('disc_spring_model', models.CharField(max_length=100, verbose_name='碟簧型号')),
                ('application_date', models.DateField(verbose_name='申请日期')),
                ('displacement_2mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2mm位移检验记录(kN)')),
                ('displacement_2_5mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='2.5mm位移检验记录(kN)')),
                ('inspector_name', models.CharField(max_length=50, verbose_name='检验人')),
                ('inspection_time', models.DateTimeField(verbose_name='检验时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_spring_data', to='tasks.subtask', verbose_name='子任务')),
            ],
            options={
                'verbose_name': '碟簧试验数据',
                'verbose_name_plural': '碟簧试验数据',
                'db_table': 'disc_spring_test_data',
                'ordering': ['-application_date', '-created_at'],
            },
        ),
    ]
