# Generated by Django 4.2.7 on 2025-11-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_testtypefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(help_text='自动生成，格式：类型代码前两位+日期+序号', max_length=50, unique=True, verbose_name='试验编号')),
                ('test_data', models.JSONField(default=dict, help_text='根据试验类型字段配置存储的动态字段数据', verbose_name='试验数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_test_data', to='tasks.subtask', verbose_name='子任务')),
            ],
            options={
                'verbose_name': '通用试验数据',
                'verbose_name_plural': '通用试验数据',
                'db_table': 'generic_test_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subtask', '-created_at'], name='generic_tes_subtask_4eec08_idx')],
            },
        ),
    ]
