# Generated by Django 4.2.7 on 2025-11-13 09:17

from django.db import migrations


def add_disc_spring_fields(apps, schema_editor):
    """为碟簧试验类型添加字段配置"""
    TestType = apps.get_model('tasks', 'TestType')
    TestTypeField = apps.get_model('tasks', 'TestTypeField')
    
    # 查找碟簧试验类型
    try:
        disc_spring_type = TestType.objects.get(code='DH_test')
    except TestType.DoesNotExist:
        print('警告：未找到碟簧试验类型 (DH_test)，跳过字段配置创建')
        return
    
    # 定义碟簧试验的字段配置
    fields_config = [
        {
            'field_name': '批次号',
            'field_code': 'batch_number',
            'field_type': 'text',
            'is_required': True,
            'order': 1,
            'placeholder': '请输入批次号',
        },
        {
            'field_name': '本批次总数',
            'field_code': 'batch_total',
            'field_type': 'number',
            'is_required': True,
            'order': 2,
            'placeholder': '请输入本批次总数',
        },
        {
            'field_name': '试验数量',
            'field_code': 'test_quantity',
            'field_type': 'number',
            'is_required': True,
            'order': 3,
            'placeholder': '请输入试验数量',
        },
        {
            'field_name': '供应商',
            'field_code': 'supplier',
            'field_type': 'text',
            'is_required': False,
            'order': 4,
            'placeholder': '请输入供应商名称',
        },
        {
            'field_name': '碟簧型号',
            'field_code': 'disc_spring_model',
            'field_type': 'text',
            'is_required': True,
            'order': 5,
            'placeholder': '请输入碟簧型号',
        },
        {
            'field_name': '申请日期',
            'field_code': 'application_date',
            'field_type': 'date',
            'is_required': True,
            'order': 6,
        },
        {
            'field_name': '2mm位移检验记录(kN)',
            'field_code': 'displacement_2mm',
            'field_type': 'decimal',
            'is_required': False,
            'order': 7,
            'placeholder': '请输入2mm位移检验记录',
        },
        {
            'field_name': '2.5mm位移检验记录(kN)',
            'field_code': 'displacement_2_5mm',
            'field_type': 'decimal',
            'is_required': False,
            'order': 8,
            'placeholder': '请输入2.5mm位移检验记录',
        },
        {
            'field_name': '检验人',
            'field_code': 'inspector_name',
            'field_type': 'text',
            'is_required': True,
            'order': 9,
            'placeholder': '请输入检验人姓名',
        },
        {
            'field_name': '检验时间',
            'field_code': 'inspection_time',
            'field_type': 'datetime',
            'is_required': True,
            'order': 10,
        },
        {
            'field_name': '备注',
            'field_code': 'remarks',
            'field_type': 'textarea',
            'is_required': False,
            'order': 11,
            'placeholder': '请输入备注信息',
        },
    ]
    
    # 创建字段配置
    for field_config in fields_config:
        TestTypeField.objects.create(
            test_type=disc_spring_type,
            **field_config
        )
    
    print(f'✅ 已为碟簧试验类型创建 {len(fields_config)} 个字段配置')


def remove_disc_spring_fields(apps, schema_editor):
    """回滚操作：删除碟簧试验字段配置"""
    TestType = apps.get_model('tasks', 'TestType')
    TestTypeField = apps.get_model('tasks', 'TestTypeField')
    
    try:
        disc_spring_type = TestType.objects.get(code='DH_test')
        TestTypeField.objects.filter(test_type=disc_spring_type).delete()
        print('✅ 已删除碟簧试验字段配置')
    except TestType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_generictestdata'),
    ]

    operations = [
        migrations.RunPython(add_disc_spring_fields, remove_disc_spring_fields),
    ]
