# Generated by Django 4.2.7 on 2026-01-05 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_add_disc_spring_field_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='level_type',
            field=models.IntegerField(choices=[(1, '总试验类型'), (2, '分试验类型')], default=1, verbose_name='类型级别'),
        ),
        migrations.AddField(
            model_name='testtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='tasks.testtype', verbose_name='所属总类型'),
        ),
    ]
