# Generated by Django 4.2.7 on 2026-01-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_testtype_level_type_testtype_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='product_model',
            field=models.CharField(default='', max_length=20, verbose_name='产品型号'),
        ),
        migrations.AddField(
            model_name='testtask',
            name='product_name',
            field=models.CharField(default='', max_length=50, verbose_name='产品名称'),
        ),
    ]
