# Generated by Django 4.2.7 on 2026-01-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_testtask_product_model_testtask_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='product_model',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='产品型号'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='产品名称'),
        ),
    ]
