# Generated by Django 4.2.7 on 2026-01-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_testtask_product_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='description',
            field=models.TextField(blank=True, verbose_name='任务描述'),
        ),
    ]
