# Generated by Django 4.2.7 on 2026-01-05 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0013_alter_testtask_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_reports/%Y/%m/%d/', verbose_name='报告文件')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('size', models.PositiveIntegerField(verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tasks.testtask', verbose_name='试验任务')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '试验任务报告',
                'verbose_name_plural': '试验任务报告',
                'db_table': 'test_task_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
