# Generated by Django 4.2.7 on 2026-02-04 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0014_testtaskreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='actual_end_date',
            field=models.DateField(blank=True, help_text='任务实际完成的日期', null=True, verbose_name='实际结束日期'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='actual_start_date',
            field=models.DateField(blank=True, help_text='任务实际开始执行的日期', null=True, verbose_name='实际开始日期'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='负责执行此任务的工程师或技术人员', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='description',
            field=models.TextField(blank=True, help_text='对试验任务的详细描述和要求', verbose_name='任务描述'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='end_date',
            field=models.DateField(help_text='计划完成任务的日期', verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='priority',
            field=models.ForeignKey(help_text='任务优先级，影响任务的处理顺序和资源分配', on_delete=django.db.models.deletion.CASCADE, to='tasks.prioritytype', verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='product_model',
            field=models.CharField(blank=True, default='', help_text='产品的具体型号规格', max_length=20, verbose_name='产品型号'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='product_name',
            field=models.CharField(blank=True, default='', help_text='需要进行试验的产品名称', max_length=50, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='当任务被拒绝或退回时填写的理由说明', verbose_name='拒绝理由'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='requester',
            field=models.ForeignKey(help_text='创建此任务的用户', on_delete=django.db.models.deletion.CASCADE, related_name='requested_tasks', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='requester_department',
            field=models.CharField(blank=True, default='', help_text='申请人所在的部门或单位', max_length=100, verbose_name='申请人部门'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='requester_name',
            field=models.CharField(blank=True, default='', help_text='申请人的真实姓名', max_length=100, verbose_name='申请人姓名'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='requester_phone',
            field=models.CharField(blank=True, default='', help_text='申请人的联系电话', max_length=20, verbose_name='申请人手机号'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='start_date',
            field=models.DateField(help_text='计划开始执行任务的日期', verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='status',
            field=models.ForeignKey(help_text='当前任务的状态，如待处理、进行中、待审核等', on_delete=django.db.models.deletion.CASCADE, to='tasks.taskstatus', verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='task_name',
            field=models.CharField(help_text='试验任务的名称，简明扼要地描述试验目的', max_length=200, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='task_number',
            field=models.CharField(help_text='系统自动生成的唯一任务编号，格式：TASK-YYYYMMDD-序号', max_length=50, unique=True, verbose_name='任务编号'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='test_outline',
            field=models.TextField(blank=True, help_text='试验的具体大纲和要求，文本格式', verbose_name='试验大纲'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='test_outline_file',
            field=models.FileField(blank=True, help_text='上传试验大纲文件，支持PDF、Word等格式', null=True, upload_to='test_outlines/', verbose_name='试验大纲文件'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='test_report',
            field=models.TextField(blank=True, help_text='试验结果报告，文本格式（历史遗留字段）', verbose_name='试验报告'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='test_report_file',
            field=models.FileField(blank=True, help_text='上传试验报告文件，支持PDF、Word等格式（历史遗留字段）', null=True, upload_to='test_reports/', verbose_name='试验报告文件'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='test_type',
            field=models.ForeignKey(help_text='选择试验类型，决定试验的具体流程和要求', on_delete=django.db.models.deletion.CASCADE, to='tasks.testtype', verbose_name='试验类型'),
        ),
        migrations.AddIndex(
            model_name='generictestdata',
            index=models.Index(fields=['test_number'], name='generic_tes_test_nu_f1f5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='generictestdata',
            index=models.Index(fields=['-created_at'], name='generic_tes_created_e88a14_idx'),
        ),
    ]
