# Generated by Django 4.2.7 on 2026-02-06 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0015_alter_testtask_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtask',
            name='test_process_description',
            field=models.TextField(blank=True, default='', help_text='记录试验过程中的详细步骤、观察结果和关键参数', verbose_name='试验过程描述'),
        ),
        migrations.CreateModel(
            name='TestTaskProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='描述内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_history', to='tasks.testtask', verbose_name='试验任务')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '试验过程历史',
                'verbose_name_plural': '试验过程历史',
                'db_table': 'test_task_process_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
