# Generated by Django 4.2.7 on 2026-02-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_testtask_test_process_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['test_type', 'status'], name='sub_tasks_test_ty_3456cd_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['parent_task'], name='sub_tasks_parent__abb930_idx'),
        ),
        migrations.AddIndex(
            model_name='testtask',
            index=models.Index(fields=['test_type', 'status'], name='test_tasks_test_ty_477e36_idx'),
        ),
        migrations.AddIndex(
            model_name='testtask',
            index=models.Index(fields=['status', 'end_date'], name='test_tasks_status__8068f0_idx'),
        ),
        migrations.AddIndex(
            model_name='testtask',
            index=models.Index(fields=['created_at'], name='test_tasks_created_2011c6_idx'),
        ),
    ]
