# Generated by Django 4.2.7 on 2026-02-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_subtask_sub_tasks_test_ty_3456cd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generictestdata',
            name='subtask',
        ),
        migrations.DeleteModel(
            name='DiscSpringTestData',
        ),
        migrations.DeleteModel(
            name='GenericTestData',
        ),
    ]
