# Generated by Django 4.2.7 on 2026-02-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_generictestdata_subtask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskdata',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, help_text='存储非批量录入的自定义字段数据', verbose_name='元数据'),
        ),
        migrations.AddField(
            model_name='testtypefield',
            name='is_batch_input_enabled',
            field=models.BooleanField(default=True, help_text='开启后，该字段将出现在批量数据录入界面；关闭后，仅在子任务详情中单独显示', verbose_name='启用批量录入'),
        ),
    ]
