# Generated by Django 4.2.7 on 2026-02-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_subtaskdata_meta_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtypefield',
            name='is_query_field',
            field=models.BooleanField(default=True, help_text='控制该字段是否作为搜索结果列展示', verbose_name='是否为查询字段'),
        ),
        migrations.AddField(
            model_name='testtypefield',
            name='is_search_field',
            field=models.BooleanField(default=False, help_text='控制该字段是否参与搜索过滤', verbose_name='是否为搜索条件'),
        ),
    ]
