# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.CharField(max_length=50, unique=True, verbose_name='工具编号')),
                ('name', models.CharField(max_length=200, verbose_name='工具名称')),
                ('type', models.CharField(max_length=100, verbose_name='工具类型')),
                ('model', models.CharField(max_length=100, verbose_name='工具型号')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='采购价格')),
                ('status', models.CharField(choices=[('available', '可用'), ('borrowed', '已借出'), ('maintenance', '维护中'), ('lost', '丢失'), ('retired', '已报废')], default='available', max_length=20, verbose_name='工具状态')),
                ('location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('specifications', models.TextField(verbose_name='技术规格')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='材质')),
                ('dimensions', models.CharField(blank=True, max_length=200, verbose_name='尺寸规格')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='重量(kg)')),
                ('accuracy', models.CharField(blank=True, max_length=50, verbose_name='精度')),
                ('measurement_range', models.CharField(blank=True, max_length=100, verbose_name='测量范围')),
                ('last_calibration_date', models.DateField(blank=True, null=True, verbose_name='上次校准日期')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='下次校准日期')),
                ('calibration_interval', models.IntegerField(default=365, verbose_name='校准间隔(天)')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
                'db_table': 'tools',
                'ordering': ['tool_id'],
            },
        ),
        migrations.CreateModel(
            name='ToolBorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(verbose_name='借用日期')),
                ('expected_return_date', models.DateField(verbose_name='预期归还日期')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='实际归还日期')),
                ('borrow_purpose', models.CharField(max_length=200, verbose_name='借用目的')),
                ('status', models.CharField(choices=[('active', '借用中'), ('returned', '已归还'), ('overdue', '逾期'), ('lost', '丢失')], default='active', max_length=20, verbose_name='借用状态')),
                ('return_condition', models.CharField(blank=True, choices=[('normal', '正常'), ('damaged', '损坏'), ('lost', '丢失')], max_length=20, verbose_name='归还时状态')),
                ('borrow_notes', models.TextField(blank=True, verbose_name='借用备注')),
                ('return_notes', models.TextField(blank=True, verbose_name='归还备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工具借用记录',
                'verbose_name_plural': '工具借用记录',
                'db_table': 'tool_borrow_records',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='ToolCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField(verbose_name='校准日期')),
                ('calibration_agency', models.CharField(max_length=200, verbose_name='校准机构')),
                ('calibration_standard', models.CharField(max_length=200, verbose_name='校准标准')),
                ('calibration_method', models.TextField(verbose_name='校准方法')),
                ('environmental_conditions', models.TextField(verbose_name='环境条件')),
                ('calibration_result', models.CharField(choices=[('pass', '合格'), ('fail', '不合格'), ('limited', '有限制使用')], max_length=20, verbose_name='校准结果')),
                ('measurement_uncertainty', models.CharField(blank=True, max_length=100, verbose_name='测量不确定度')),
                ('calibration_data', models.TextField(verbose_name='校准数据')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='证书编号')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='tool_calibration/', verbose_name='校准证书')),
                ('valid_until', models.DateField(verbose_name='有效期至')),
                ('next_calibration_date', models.DateField(verbose_name='下次校准日期')),
                ('calibration_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='校准费用')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工具校准记录',
                'verbose_name_plural': '工具校准记录',
                'db_table': 'tool_calibration',
                'ordering': ['-calibration_date'],
            },
        ),
    ]
