# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcalibration',
            name='calibration_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='校准人员'),
        ),
        migrations.AddField(
            model_name='toolcalibration',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool', verbose_name='工具'),
        ),
        migrations.AddField(
            model_name='toolborrowrecord',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tool_borrows', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='toolborrowrecord',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_tools', to=settings.AUTH_USER_MODEL, verbose_name='借用人'),
        ),
        migrations.AddField(
            model_name='toolborrowrecord',
            name='test_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.testtask', verbose_name='关联试验任务'),
        ),
        migrations.AddField(
            model_name='toolborrowrecord',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool', verbose_name='工具'),
        ),
        migrations.AddField(
            model_name='tool',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
