# Generated by Django 4.2.7 on 2026-01-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='采购日期'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='采购价格'),
        ),
    ]
