# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='制造商')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='采购价格')),
                ('warranty_period', models.IntegerField(verbose_name='保修期(月)')),
                ('warranty_end_date', models.DateField(verbose_name='保修到期日期')),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '维护中'), ('repair', '维修中'), ('retired', '已报废')], default='available', max_length=20, verbose_name='设备状态')),
                ('location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('specifications', models.TextField(verbose_name='技术规格')),
                ('operating_manual', models.FileField(blank=True, null=True, upload_to='equipment_manuals/', verbose_name='操作手册')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次维护日期')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('maintenance_interval', models.IntegerField(default=30, verbose_name='维护间隔(天)')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'equipment',
                'ordering': ['equipment_id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('routine', '例行维护'), ('preventive', '预防性维护'), ('corrective', '纠正性维护'), ('emergency', '紧急维护')], max_length=20, verbose_name='维护类型')),
                ('maintenance_date', models.DateField(verbose_name='维护日期')),
                ('maintenance_content', models.TextField(verbose_name='维护内容')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='更换部件')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='维护费用')),
                ('maintenance_result', models.CharField(choices=[('completed', '完成'), ('pending', '待完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='维护结果')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备维护记录',
                'verbose_name_plural': '设备维护记录',
                'db_table': 'equipment_maintenance',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始使用时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束使用时间')),
                ('usage_purpose', models.CharField(max_length=200, verbose_name='使用目的')),
                ('usage_notes', models.TextField(blank=True, verbose_name='使用说明')),
                ('equipment_condition', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常'), ('damaged', '损坏')], default='normal', max_length=20, verbose_name='设备状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备使用记录',
                'verbose_name_plural': '设备使用记录',
                'db_table': 'equipment_usage_records',
                'ordering': ['-start_time'],
            },
        ),
    ]
