# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiSlipTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='样品编号')),
                ('test_date', models.DateField(verbose_name='试验日期')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度(°C)')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='湿度(%)')),
                ('friction_coefficient', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='摩擦系数')),
                ('slip_resistance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='防滑阻力(N)')),
                ('result', models.CharField(max_length=20, verbose_name='试验结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '防滑试验数据',
                'verbose_name_plural': '防滑试验数据',
                'db_table': 'anti_slip_test_data',
            },
        ),
        migrations.CreateModel(
            name='CompressionTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='样品编号')),
                ('test_date', models.DateField(verbose_name='试验日期')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度(°C)')),
                ('compression_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='压缩速率(mm/min)')),
                ('compression_strength', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='压缩强度(MPa)')),
                ('compression_modulus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='压缩模量(GPa)')),
                ('deformation', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='变形量(mm)')),
                ('result', models.CharField(max_length=20, verbose_name='试验结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '压缩试验数据',
                'verbose_name_plural': '压缩试验数据',
                'db_table': 'compression_test_data',
            },
        ),
        migrations.CreateModel(
            name='CorrosionTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='样品编号')),
                ('test_date', models.DateField(verbose_name='试验日期')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度(°C)')),
                ('corrosive_medium', models.CharField(max_length=100, verbose_name='腐蚀介质')),
                ('exposure_time', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='暴露时间(h)')),
                ('weight_loss', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='失重(g)')),
                ('corrosion_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='腐蚀速率(mm/year)')),
                ('corrosion_depth', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='腐蚀深度(mm)')),
                ('result', models.CharField(max_length=20, verbose_name='试验结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '腐蚀试验数据',
                'verbose_name_plural': '腐蚀试验数据',
                'db_table': 'corrosion_test_data',
            },
        ),
        migrations.CreateModel(
            name='CreepTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='样品编号')),
                ('test_date', models.DateField(verbose_name='试验日期')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度(°C)')),
                ('applied_stress', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='施加应力(MPa)')),
                ('test_duration', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='试验时间(h)')),
                ('initial_strain', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='初始应变')),
                ('final_strain', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='最终应变')),
                ('creep_rate', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='蠕变速率(s⁻¹)')),
                ('result', models.CharField(max_length=20, verbose_name='试验结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '蠕变试验数据',
                'verbose_name_plural': '蠕变试验数据',
                'db_table': 'creep_test_data',
            },
        ),
        migrations.CreateModel(
            name='FatigueTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='样品编号')),
                ('test_date', models.DateField(verbose_name='试验日期')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度(°C)')),
                ('frequency', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='频率(Hz)')),
                ('stress_ratio', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='应力比')),
                ('max_stress', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='最大应力(MPa)')),
                ('min_stress', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='最小应力(MPa)')),
                ('cycles_to_failure', models.BigIntegerField(verbose_name='破坏循环次数')),
                ('result', models.CharField(max_length=20, verbose_name='试验结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '疲劳试验数据',
                'verbose_name_plural': '疲劳试验数据',
                'db_table': 'fatigue_test_data',
            },
        ),
        migrations.CreateModel(
            name='HardnessTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='样品编号')),
                ('test_date', models.DateField(verbose_name='试验日期')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度(°C)')),
                ('test_method', models.CharField(max_length=50, verbose_name='试验方法')),
                ('load_force', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='试验力(N)')),
                ('hardness_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='硬度值')),
                ('indentation_depth', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='压痕深度(mm)')),
                ('result', models.CharField(max_length=20, verbose_name='试验结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '硬度试验数据',
                'verbose_name_plural': '硬度试验数据',
                'db_table': 'hardness_test_data',
            },
        ),
        migrations.CreateModel(
            name='MetalImpactTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='样品编号')),
                ('test_date', models.DateField(verbose_name='试验日期')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度(°C)')),
                ('impact_energy', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='冲击能量(J)')),
                ('impact_strength', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='冲击强度(J/cm²)')),
                ('fracture_type', models.CharField(max_length=50, verbose_name='断裂类型')),
                ('result', models.CharField(max_length=20, verbose_name='试验结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '金属冲击试验数据',
                'verbose_name_plural': '金属冲击试验数据',
                'db_table': 'metal_impact_test_data',
            },
        ),
        migrations.CreateModel(
            name='MetalTensileTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, verbose_name='样品编号')),
                ('test_date', models.DateField(verbose_name='试验日期')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度(°C)')),
                ('strain_rate', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='应变速率(s⁻¹)')),
                ('tensile_strength', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='抗拉强度(MPa)')),
                ('yield_strength', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='屈服强度(MPa)')),
                ('elongation', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='延伸率(%)')),
                ('elastic_modulus', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='弹性模量(GPa)')),
                ('result', models.CharField(max_length=20, verbose_name='试验结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='试验任务')),
            ],
            options={
                'verbose_name': '金属拉伸试验数据',
                'verbose_name_plural': '金属拉伸试验数据',
                'db_table': 'metal_tensile_test_data',
            },
        ),
    ]
