# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_initial'),
        ('test_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaltensiletestdata',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验员'),
        ),
        migrations.AddField(
            model_name='metalimpacttestdata',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='试验任务'),
        ),
        migrations.AddField(
            model_name='metalimpacttestdata',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验员'),
        ),
        migrations.AddField(
            model_name='hardnesstestdata',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='试验任务'),
        ),
        migrations.AddField(
            model_name='hardnesstestdata',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验员'),
        ),
        migrations.AddField(
            model_name='fatiguetestdata',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='试验任务'),
        ),
        migrations.AddField(
            model_name='fatiguetestdata',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验员'),
        ),
        migrations.AddField(
            model_name='creeptestdata',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='试验任务'),
        ),
        migrations.AddField(
            model_name='creeptestdata',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验员'),
        ),
        migrations.AddField(
            model_name='corrosiontestdata',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='试验任务'),
        ),
        migrations.AddField(
            model_name='corrosiontestdata',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验员'),
        ),
        migrations.AddField(
            model_name='compressiontestdata',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='试验任务'),
        ),
        migrations.AddField(
            model_name='compressiontestdata',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验员'),
        ),
        migrations.AddField(
            model_name='antisliptestdata',
            name='test_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.testtask', verbose_name='试验任务'),
        ),
        migrations.AddField(
            model_name='antisliptestdata',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='试验员'),
        ),
    ]
