# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('view', '查看'), ('export', '导出'), ('import', '导入')], max_length=20, verbose_name='操作类型')),
                ('object_type', models.CharField(max_length=50, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='对象ID')),
                ('object_repr', models.CharField(max_length=200, verbose_name='对象描述')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='变更内容')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('request_path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('document', '文档'), ('image', '图片'), ('data', '数据文件'), ('report', '报表'), ('manual', '手册'), ('certificate', '证书')], max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME类型')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='关联对象类型')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件上传记录',
                'verbose_name_plural': '文件上传记录',
                'db_table': 'file_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('notification_type', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('success', '成功')], default='info', max_length=20, verbose_name='通知类型')),
                ('category', models.CharField(choices=[('task', '任务通知'), ('equipment', '设备通知'), ('maintenance', '维护通知'), ('system', '系统通知'), ('report', '报表通知')], max_length=20, verbose_name='通知分类')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='关联对象类型')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('send_email', models.BooleanField(default=False, verbose_name='是否发送邮件')),
                ('email_sent', models.BooleanField(default=False, verbose_name='邮件是否已发送')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='邮件发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_name', models.CharField(max_length=200, verbose_name='备份名称')),
                ('backup_type', models.CharField(choices=[('full', '完整备份'), ('incremental', '增量备份'), ('differential', '差异备份')], max_length=20, verbose_name='备份类型')),
                ('backup_config', models.JSONField(verbose_name='备份配置')),
                ('backup_path', models.CharField(max_length=500, verbose_name='备份路径')),
                ('status', models.CharField(choices=[('running', '备份中'), ('completed', '已完成'), ('failed', '备份失败')], default='running', max_length=20, verbose_name='备份状态')),
                ('file_count', models.IntegerField(default=0, verbose_name='文件数量')),
                ('backup_size', models.BigIntegerField(default=0, verbose_name='备份大小(字节)')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='备份耗时')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统备份记录',
                'verbose_name_plural': '系统备份记录',
                'db_table': 'system_backups',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('config_value', models.TextField(verbose_name='配置值')),
                ('config_type', models.CharField(choices=[('system', '系统配置'), ('email', '邮件配置'), ('notification', '通知配置'), ('security', '安全配置'), ('backup', '备份配置')], max_length=20, verbose_name='配置类型')),
                ('description', models.TextField(verbose_name='配置描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_editable', models.BooleanField(default=True, verbose_name='是否可编辑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_config',
            },
        ),
    ]
