# Generated by Django 4.2.7 on 2025-10-25 00:00

from django.db import migrations

def create_initial_departments(apps, schema_editor):
    Department = apps.get_model('users', 'Department')
    initial_departments = [
        {'name': '试验室', 'code': 'LAB', 'description': '试验室部门'},
        {'name': '研发部', 'code': 'R&D', 'description': '研发部门'},
        {'name': '质量部', 'code': 'QA', 'description': '质量管理部门'},
    ]
    for dept_data in initial_departments:
        Department.objects.create(**dept_data)

def reverse_initial_departments(apps, schema_editor):
    Department = apps.get_model('users', 'Department')
    Department.objects.filter(code__in=['LAB', 'R&D', 'QA']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_departments, reverse_initial_departments),
    ]