# Generated by Django 4.2.7 on 2025-10-25 00:00

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_initial_admin_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Department = apps.get_model('users', 'Department')
    
    # 检查管理员用户是否已存在
    if User.objects.filter(username='admin').exists():
        return
    
    # 获取试验室部门
    try:
        lab_dept = Department.objects.get(code='LAB')
    except Department.DoesNotExist:
        lab_dept = None
    
    # 创建管理员用户
    admin_user = User(
        username='admin',
        employee_id='1001',
        first_name='系统',
        last_name='管理员',
        email='admin@example.com',
        phone='13800138001',
        department=lab_dept,
        is_staff=True,
        is_superuser=True,
        is_active=True,
    )
    admin_user.password = make_password('admin123')  # 使用加密密码
    admin_user.save()

def reverse_initial_admin_user(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_departments'),
    ]

    operations = [
        migrations.RunPython(create_initial_admin_user, reverse_initial_admin_user),
    ]