# Generated by Django 4.2.7 on 2025-10-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '系统管理员'), ('manager', '试验室主管'), ('engineer', '试验工程师'), ('equipment_manager', '设备管理员')], default='engineer', max_length=20, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', '在职'), ('inactive', '离职')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
    ]
