# Generated by Django 4.2.7 on 2025-11-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_department'),
    ]

    operations = [
    ]
