# Generated by Django 4.2.7 on 2025-11-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20251110_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '系统管理员'), ('manager', '试验室主管'), ('engineer', '试验工程师'), ('equipment_manager', '设备管理员'), ('guest', '访客')], default='engineer', max_length=20, verbose_name='角色'),
        ),
    ]
