# Generated by Django 4.2.7 on 2025-10-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200, verbose_name='报表名称')),
                ('generation_params', models.JSONField(verbose_name='生成参数')),
                ('date_range_start', models.DateField(verbose_name='数据起始日期')),
                ('date_range_end', models.DateField(verbose_name='数据结束日期')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='generating', max_length=20, verbose_name='生成状态')),
                ('output_format', models.CharField(max_length=10, verbose_name='输出格式')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='generated_reports/', verbose_name='报表文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('generation_time', models.DurationField(blank=True, null=True, verbose_name='生成耗时')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生成的报表',
                'verbose_name_plural': '生成的报表',
                'db_table': 'generated_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '查看'), ('download', '下载'), ('share', '分享')], max_length=20, verbose_name='操作类型')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '报表访问记录',
                'verbose_name_plural': '报表访问记录',
                'db_table': 'report_access',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('schedule_type', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月'), ('quarterly', '每季度'), ('yearly', '每年')], max_length=20, verbose_name='调度类型')),
                ('schedule_time', models.TimeField(verbose_name='执行时间')),
                ('schedule_config', models.JSONField(verbose_name='调度配置')),
                ('generation_params', models.JSONField(verbose_name='生成参数')),
                ('output_format', models.CharField(max_length=10, verbose_name='输出格式')),
                ('email_recipients', models.JSONField(default=list, verbose_name='邮件接收人')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='是否启用通知')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报表定时任务',
                'verbose_name_plural': '报表定时任务',
                'db_table': 'report_schedules',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('report_type', models.CharField(choices=[('task_summary', '任务汇总报表'), ('equipment_usage', '设备使用报表'), ('test_data_analysis', '试验数据分析报表'), ('maintenance_schedule', '维护计划报表'), ('resource_utilization', '资源利用率报表'), ('quality_control', '质量控制报表')], max_length=30, verbose_name='报表类型')),
                ('description', models.TextField(verbose_name='模板描述')),
                ('template_config', models.JSONField(verbose_name='模板配置')),
                ('sql_query', models.TextField(blank=True, verbose_name='SQL查询语句')),
                ('output_formats', models.JSONField(default=list, verbose_name='支持的输出格式')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报表模板',
                'verbose_name_plural': '报表模板',
                'db_table': 'report_templates',
            },
        ),
    ]
